### PR TITLE
add "asar": true (default behaviour)

### PR DESCRIPTION
**Pull request by OwenBrotherwood**
Indicates where to disable asar.
"asar" : true gives default behaviour, use of asar archieve
"asar": false, allows encapsulated code to use files files directly and not the asar archive

Owen Brotherwood

### CODE REVIEW

**Comment by szwacz** [comment]
Thank you for this pull request as well :) However... I don't fully understand the problem it tries to solve. Asar is enabled by defaul in `electron-builder`, so it will just work without this option specified. If the problem is that it's difficult to find those options in the docs then maybe problem lies more in the documentation?

**Comment by OwenBrotherwood** [comment]
Basically, a time saver for people wanting to use your code to encapsulate others work, be it all work or just a dependancy the feel they need to use but does not support asar.
Another person would be yourself, for those who are trying your code and then ask questions (and possibly move on) https://github.com/szwacz/electron-boilerplate/issues/129

**Comment by OwenBrotherwood** [comment]
I think this issue, https://github.com/szwacz/electron-boilerplate/issues/170#issue-158520506, with a comment about "null path" indicates an  asar problem

**Comment by szwacz** [comment]
See https://github.com/szwacz/electron-boilerplate/pull/227

**Pull request closed without merging**
