### PR TITLE
Auto update

### PR DESCRIPTION
**Pull request by wcurtis**

### CODE REVIEW

**Comment by carlosperate** [comment]
Please correct me if I am wrong, wouldn't this be informing the _users_ of an available update to the electron framework (no the app)? in that case, how would that update work with the packaged/installed applications?

**Comment by black-snow** [comment]
Is there any information on what this PR is good for?

**Comment by wcurtis** [comment]
Sorry everyone, this was supposed to be a PR on my forked repo. Oops! 

Closing

**Comment by szwacz** [comment]
What doesn't mean neat integration of autoupdate to this project wouldn't be welcome with open hands ;)

**Comment by wcurtis** [comment]
Ha - I like the way you think :) There's a few projects that I'm eyeballing to handle auto updates, each approach it a bit differently. I'll open an issue once I play around with each and have a better idea of what might make sense to add to this boilerplate.

Options I've found so far
- [Native Electron](https://github.com/atom/electron/blob/master/docs/api/auto-updater.md)
- [Via npm](https://github.com/evolvelabs/electron-updater)
- [Via github](https://github.com/GitbookIO/nuts)

**Pull request closed without merging**
