### PR TITLE
Travis cache

### PR DESCRIPTION
**Pull request by rodrigok**

### CODE REVIEW

**Comment by black-snow** [comment]
@rodrigok Why all those PRs?

**Comment by rodrigok** [comment]
@black-snow Sorry, as we are a fork of your PR, GitHub always point new PRs to your repo.

We are planing to delete our repo and create a new one to remote the fork link. But we will lose all issues, starts, etc.

**Comment by szwacz** [comment]
I did small googling on that and indeed this process is without a reason very difficult. @rodrigok maybe you should try to contack GitHub staff and see if they can help?

**Comment by rodrigok** [comment]
@szwacz I did, waiting...

**Comment by rodrigok** [comment]
@szwacz Just checked and it was done 45 minutes ago 😄  

No more undesired PRs 🎉

**Comment by black-snow** [comment]
@rodrigok Thanks ;)

**Pull request closed without merging**
