### PR TITLE
Travis & Appveyor CI badge and support

### PR DESCRIPTION
**Pull request by misteral**
Script and travis-ci config.

### CODE REVIEW

**Comment by black-snow** [comment]
Thanks for the PR. *IMHO* more node versions should be tested - not just 4.5.0.

**Comment by blainesch** [comment]
I'd say *less* should be tested. This boilerplate uses electron `1.3.3` which is node `6.3.0`.

If we wanted more of something, I'd say more operating systems. Windows often breaks so adding appveyor to this would also be helpful.

**Comment by misteral** [comment]
@blainesch I switch to node 6.3.0 and add appveyor support. Also add e2e tests.

**Comment by black-snow** [comment]
Right, we use node implicitly so no need to test different versions. My bad.

**Comment by szwacz** [comment]
Thank you @misteral for this PR. There were PR's to support CI systems in the past for electron-boilerplate but I resisted reasoning that
1. (in my feeling) not many people will actually use those
2. because most of uses of this project are for commercial purposes and I have no interest in advertising CIs for no gain ;)

But as I see the topic returns like a boomerang. So I might change my mind about it.

All voices in the discussion are welcome.

**Comment by discordier** [comment]
@szwacz Maybe you are mistaken on what this PR want's to introduce and what CI is all about.

The CI systems get triggered on every push, PR and tag (when you activate them). They will fetch the sources from github, run the tests and  mark the result as commit state right here on github.
They help you as maintainer as a first defense line in deciding on PRs as not every developer (in my experience, almost none) out there runs tests before pushing a PR.

On the general topic, I rather use software using continuous integration systems than those not doing so, as I can examine by looking at the source and in the CI logs if the software is in good state before even considering the usage (or the refraining of).

In the end, when you accept this PR (which I suggest to do) you will have to enable the travis hook in the repository settings at github.

**Comment by szwacz** [comment]
Ok, ok! ;) If everyone wants it then it's here.
Thanks for your contributions!

**Pull request merged**
