### PR TITLE
Add preGypFix option when running rebuild_native_modules.js

### PR DESCRIPTION
**Pull request by timfish**
There is a known issue with `node-pre-gyp` that prevents it from correctly locating some native modules. I've found a couple which fail to rebuild using `rebuild_native_modules` (`node-serialport` being the most important to me, but there are more).

With this PR, users can an argument which ignores the incorrect `shouldRebuildNativeModules` result and calls `preGypFixRun` in `electron-rebuild` after rebuild.

```
    "postinstall": "node ../tasks/rebuild_native_modules preGypFix"
```

Let me know if you're not happy with any of it or you want me to add a couple of lines to the readme.

### CODE REVIEW

**Comment by szwacz** [comment]
Hi and thanks for this PR.

I have to ask one question as the starter: is there any willing to solve this issue in node-pre-gyp internals?

**Comment by timfish** [comment]
As far as I can tell there's willing, its just taking a while:
https://github.com/mapbox/node-pre-gyp/pull/187
https://github.com/mapbox/node-pre-gyp/issues/189

It might be helpful enough just to have this PR here open as reference to anybody who needs it.

**Comment by szwacz** [comment]
Thanks. Yes, so as you said I will leave this open as a reference and see how the situation unwindws.

**Comment by szwacz** [comment]
Looks like the problem has been resolved: https://github.com/mapbox/node-pre-gyp/pull/187 does it work now without the hack?

**Comment by szwacz** [comment]
This is now handled by electron-builder, so even if the problem still exists patches need to be applied to that tool.

**Pull request closed without merging**
