### PR TITLE
Add wix installer support.

### PR DESCRIPTION
**Pull request by santriseus**
Hi, I`ve added the possibility to create a wix installer for Windows version:
Both the .msi file and the default .exe bootstrapper with bundled .msi file.

### CODE REVIEW

**Comment by szwacz** [comment]
Hi. I see you did a lot of work here but I don't know what to do with it.
My concernes:
- If I merge it I'll be bound to support two release processes for windows (more testing).
- I also don't think boilerplate app should give people choice, then questions like "what should I pick, NSIS or WIX?" will start to appear.

Why you decided to pick wix? Does it give you something NSIS can't offer? Then we can talk about getting rid of NSIS and supporting only wix.

All thoughts are welcome!

**Comment by carlosperate** [comment]
>Why you decided to pick wix? Does it give you something NSIS can't offer? Then we can talk about getting rid of NSIS and supporting only wix.

This looks like the best approach to me, I think these types of boiler plates should stay as slim as possible.

**Comment by szwacz** [comment]
Closing this as apparently the discussion has died.

**Comment by tyv** [comment]
JFYI I am going to use WIX with this boilerplate, because we need MSI as build result. And this is not supported in NSIS.

**Comment by kof** [comment]
@santriseus maybe it makes sense to publish electron-boilerplate-msi as a separate project?

**Comment by kof** [comment]
or @szwacz merge it and remove NSIS, so you have only WIX to support

**Comment by santriseus** [comment]
I`m agree with @szwarc about the slim boilerplate structure. Sorry for my silence.
Also now we have https://github.com/electron/windows-installer
It utilizes the power of Squirrel, which actually utilizes the WiX and allows to build .msi installers.

**Comment by tyv** [comment]
thanks for input!
JFYI it is not all so simple with Squirrel  
https://github.com/Squirrel/Squirrel.Windows/issues/241
> if your app needs to install a device driver or be in Program Files, Squirrel won't work for you

**Comment by szwacz** [comment]
@tyv do you need msi file because it's required by some distribution system/store?

About Squirrel. I'm not following what this comment means by 'Program Files', aren't all aplications by default installed to Program Files?
Device drivers? Does anyone have an example of use case for that.

**Comment by tyv** [comment]
@szwacz I need msi because admins distribute (I really don't know how exactly, think it is called Group policy) them for large companies and our product is required to support it, so it is not about drivers but about group deploy.
Also why I decide to do not try using Squirrel right now is an extra dependency without any benefit for our case as we don't need autoupdates.

**Comment by tyv** [comment]
and thanks to this PR and @santriseus we got working installer in one day.
also WIX is more powerful than NSIS out of the box I think, at least it propose to chose installation folder :) and has more styling options

**Comment by kof** [comment]
@szwacz wix supports msi, NSIS does not. Also WIX is a way more mature solution and supports a huge amount of options. It is clearly a  better option over NSIS, you would need to support WIX only. If you need help, we have a fully functional repository. https://github.com/ubergrape/grape-electron

**Comment by black-snow** [comment]
@kof We chose to use electron-builder. Guess they'd be happy if you filed a PR that ads wix-support (currently electron-builder supports NSIS and Squirrel).

**Pull request closed without merging**
