### PR TITLE
Mocha + Travis

### PR DESCRIPTION
**Pull request by blainesch**
It passes! :D :beers: 

https://travis-ci.org/blainesch/electron-boilerplate/builds/117912715

Related: #135 #136 and #138

### CODE REVIEW

**Comment by blainesch** [comment]
Oh, it should be noted, this makes it so it runs the tests in a headless browser not electron. I think this should be fine.

Also, do we expect anybody who forked this or used this as their base to pull in the new changes? It allows for CI now, but converting somebody like [rocket chat](https://github.com/RocketChat/Rocket.Chat.Electron) to switch to mocha might be a hard switch.

**Comment by szwacz** [comment]
Awesome!

It works in electron, but as you said headlessly (because it's main process which has no window). I believe there is no problem in opening real window from there if this is necessary.

About switching already existing projects from jasmine to mocha - well every project has it's breaking changes once in awhile. Integration with mocha is sooooo much smoother (thanks to `electron-mocha`) than with jasmine, that it's a shame not to take the advantage.

**Comment by szwacz** [comment]
The only noticeable change I've done is to not include travis file in this project, and instead [link to full docs](https://github.com/atom/electron/blob/master/docs/tutorial/testing-on-headless-ci.md), so people can have the full picture.

Thanks once again @blainesch.

**Comment by blainesch** [comment]
Thanks for the merge! :D

**Comment by blainesch** [comment]
@szwacz when is the planned merge into master for this?

**Pull request merged**
