### PR TITLE
Test the release can be built on CI.

### PR DESCRIPTION
**Pull request by blainesch**
I'm having issues building this on CI, so having this as part of the boilerplate ensures it is working correctly.

### CODE REVIEW

**Comment by szwacz** [comment]
Hi @blainesch,
May I better understand the context? What kind of errors do you get in your release process that can be spotted by CI?

**Comment by blainesch** [comment]
This asserts the app can be built. I was having issues building, so I added this to my CI. Doubly, it confirms it was working when I got it.

**Comment by szwacz** [comment]
@blainesch after rethinking I agree there is a value in knowing your build process is passing as well. But your change tests only builds on osx and linux, would you like to add it also to appveyour file so it's tested on windows as well?

**Comment by OwenBrotherwood** [comment]
Also consider the addition of npm run release.
I updated the package.json's to the latest available release, and was unable to create a release due to an error caused by "depreciated and not supported".

**Pull request closed without merging**
