### PR TITLE
Add asar to release pipeline for windows

### PR DESCRIPTION
**Pull request by ingro**
This pull request is a proposal to add asar to the release pipeline for Windows OS. Without it files with a name longer than~255 chars (not too hard with npm's nested depencies) cannot be installed (you could ignore it while installing but the app may not work properly after).

Maybe the whole process could be handled better but this is a working starting point, let me know if this makes sense!

### CODE REVIEW

**Comment by szwacz** [comment]
It looks good! Can you construct the asar file to tmp directory? I don't see the need to create separate 'dist' folder for that.

**Comment by ingro** [comment]
Yeah, as I said that was a little rough implementation, I think I can use a tmp folder as you suggested. Anyway I found an issue with .exe files packed into asar (https://github.com/atom/asar/issues/35), so I don't know if this will be a good viable default option, even if it solves the path too long error... Working on Windows sucks sometimes :(

**Comment by szwacz** [comment]
Executables in node_modules are much less common than path too long, so I think packing to asar is definatelly better tradeoff for boilerplate for most tipical applications.

**Comment by ingro** [comment]
Well I guess you're right, I will try to improve my PR soon to use a temp folder. Another tool that may be worh to be included its [modclean](https://www.npmjs.com/package/modclean), which deletes unneeded files from `node_modules` folder. On a project that I'm working on lately took down the size of the folder from ~26M to ~20M. I will open a new PR when I figure out how to integrate it!

**Comment by szwacz** [comment]
About asar - Cool. 

About modclean - I wouldn't incorporate it into this project for few reasons.
1. Deleting files might make modules unstable.
2. This is cool, but non-essential feature.
3. I don't want to overly complicate this project so it stayes as easy to grasp for newcomers as possible.
You can propose this tool for https://github.com/sindresorhus/awesome-electron so people are aware it exists :)

**Comment by ingro** [comment]
It makes sense! Anyway I updated my PR, I figured out I can save the `asar` archive direcly in the `tmp` folder you already created, so the copy step is no longer needed :)

**Comment by szwacz** [comment]
I've refined your code a bit and applied it to osx and linux as well. Thanks for your PR!

**Comment by ingro** [comment]
No problem, thanks for your work which helped me a lot getting started with Electron :)

**Pull request merged**
