### PR TITLE
Istanbul

### PR DESCRIPTION
**Pull request by danschultzer**
This adds [istanbul](https://github.com/gotwarlost/istanbul) code coverage, with `npm run coverage` command. It works well in the [blazing-bookkeeper](https://github.com/danschultzer/blazing-bookkeeper) repo.

### CODE REVIEW

**Comment by szwacz** [comment]
Thanks for the PR! Nice piece of code.

One question though. If changing reporter and reporter's directory is as easy as editing one config object in one file is there really a value in providing also environment variables to configure this? Or this is for some automated tools I'm not familiar with?

**Comment by danschultzer** [comment]
Thanks!

Yeah, it's for automated code coverage. In [our use case](https://github.com/danschultzer/blazing-bookkeeper/blob/master/circle.yml#L5-L6.), we need it for CircleCI to do `lcovonly` code coverage reporting, while locally running `npm run coverage` we expect it to generate the regular `html`/`text-summary` report. I think others will have the same need for changing the config dynamically in different environments.

It's kind of ugly though, and I tried to make it configurable in the script itself, but [mocha-electron doesn't yet accept](https://github.com/jprichardson/electron-mocha/blob/35426dc652613283c7b1ce236acafdf37e18e0db/mocha.js#L11) mocha [reporter options](https://github.com/mochajs/mocha/blob/4944e31ff60105815f4b314996a9861e73f6bfd2/lib/mocha.js#L88). I might look into opening a PR for mocha-electron to fix this, so we can remove the env variables and just call something like `npm test -- -R scripts/istanbul-reporter -O reporters=lcovonly`. That's why there's already `options.reporters` setting.

**Comment by danschultzer** [comment]
I found an issue in this PR, the stack trace doesn't use the source map. I'll fix it.

**Comment by danschultzer** [comment]
So the issue is in the `rollup-plugin-istanbul` package. [It doesn't return any source map](https://github.com/artberri/rollup-plugin-istanbul/blob/13174067f26ec829c0a8b4297724cafb026d141c/src/index.js#L17). There's a [4-month-old PR](https://github.com/artberri/rollup-plugin-istanbul/pull/5) to add in source maps that we could use, but I'm checking if it can be merged into master and push a new release on npm.

**Comment by danschultzer** [comment]
Got a new release for `rollup-plugin-istanbul` out today. Tests now show up with correct stack trace:

```javascript
  1) hello world greets:
     Error: Test
      at greet (/Users/dan/electron-boilerplate/app/src/hello_world/hello_world.js:2:11)
      at Context.<anonymous> (/Users/dan/electron-boilerplate/app/src/hello_world/hello_world.spec.js:8:16)
      at runCallback (timers.js:566:20)
      at tryOnImmediate (timers.js:546:5)
      at processImmediate [as _immediateCallback] (timers.js:525:5)
```

@szwacz any comments?

**Comment by szwacz** [comment]
Works great. Thanks!

**Pull request merged**
