### PR TITLE
Update chai to new major version

### PR DESCRIPTION
**Pull request by black-snow**
Many nice feature/fixes (mostly deep comparison)

### CODE REVIEW

**Comment by black-snow** [comment]
appveyor failed due to not finding `debug` oÓ

**Comment by szwacz** [comment]
appveyor fails on installation of `electron-chromedriver` about which folks in https://github.com/szwacz/electron-boilerplate/issues/270 were complaining. Intersting...

**Comment by black-snow** [comment]
Yeah, weird. Maybe we should take a look at that.

**Comment by szwacz** [comment]
I've tried the installation process on Windows 7 VM and no problems there.

**Pull request merged**
