### PR TITLE
Use path to join path instead of manually set path

### PR DESCRIPTION
**Pull request by Schultzer**
Using [node path module](https://nodejs.org/api/path.html) [`path.join()`](https://nodejs.org/api/path.html#path_path_join_paths) or [`path.resovle()`](https://nodejs.org/api/path.html#path_path_resolve_paths) is better then setting path manually.

What do you think 👀 @szwacz

### CODE REVIEW

**Comment by black-snow** [comment]
Thanks Schultzer

**Comment by szwacz** [comment]
Thank you @Schultzer but this is not correct use of `path`.
The file as I runned it turned this: `console.log(path.join('file://', __dirname, '/app.html'));` into this: `file:/Users/me/dev/my-app/app.html`. As you may see the protocol is now `file:/` with single slash. That's because `path` module is for paths in file system, not web browser protocols.

I looked how the electron guys are doing this: https://github.com/electron/electron-quick-start/blob/master/main.js and their way is indeed better. Since you already put effort into this would you like to amend your pull request with usage of `url` module like electron-quick-start is doing this?

**Comment by Schultzer** [comment]
@szwacz Thanks for the feedback. the PR is now corrected.

**Comment by szwacz** [comment]
Thanks!

**Pull request merged**
