### PR TITLE
Babel and Jspm

### PR DESCRIPTION
**Pull request by yailPeralta**
Hi i added babel as javascript transpiler and the packages manager Jspm which uses System as universal module loader, i think this is the best option.
 Best regards 
Yail.

### CODE REVIEW

**Comment by szwacz** [comment]
Hi Yali,
Oh god, where to start....

1. This project is about Electron, not about webstack. Technologies which make sense in the browser not necessarily make sense in Electorn.
2. This project wants to give people as small as possible starter pack, so they can easily grasp what Electron development is about and continuing with adding things they find useful.

From things you have included only Babel might be something to consider incorporating here. The rest unnecessarily complicates things for newcomers.

About Babel I'm also not 100% sure. In electron you care only about latest version of V8, which already have a lot of ES6 features.

**Comment by yailPeralta** [comment]
1 - Ok I think electron was made for web developers and it runs in chromium web browser so it has a lot of sense to use some technologies that we commonly use when development web applications. 
2 - is ok what you say, I think it is reasonable, but for instance the last version of v8 does not support classes, so Babel seems to be a great option to me.

Anyway you have made a great work and i'm using your boilerplate in a project, thanks a lot!. 

By the way, i have made a library for ajax requests if you want to contribute in the project improving the code or adding new features that would be great. https://github.com/yailPeralta/phyrus

Best regards Yail.
Date: Sun, 28 Jun 2015 12:10:08 -0700

**Comment by szwacz** [comment]
The good old saying states that If you want to please everyone you probably won't please a single person. That's why I want to add to this repo as little tools as possible.
But there is a good reason to support ES6 features, which will be standard within a year anyway. That's why I said adding Babel might actually have sense. If more people requests that I see no problem to add it here.

Thanks for a good word about electron-boilerplate, and keep up your good work.

**Comment by yailPeralta** [comment]
Yes that's right. You're welcome! 😊

Date: Sun, 28 Jun 2015 13:25:20 -0700

**Pull request closed without merging**
