### PR TITLE
Added extra info to installer for Windows

### PR DESCRIPTION
**Pull request by sviterok**
Hi, I've added "companyName" and version number to NSIS's configuration. Both values are coming from app's "package.json".

That information will be visible in this menu:
prog-fea
"companyName" --> "Publisher" column
version --> "Version" column

### CODE REVIEW

**Comment by szwacz** [comment]
Cool stuff! But I'd rather use already existing in package.json field "author" than invent new "companyName". Could you please do it that way? You can also remove the <email> parto of author field.

**Comment by sviterok** [comment]
Thanks! Yes, no problem. Honestly, I've just completely forgot about that "author" field.

**Comment by sviterok** [comment]
Well, It seams like that the only problem with "author" field approach is the structure of that field.

According to specs [here](https://docs.npmjs.com) and [here](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json) it could be an object with "name" field inside or it might be a string with optional email in angle brackets and URL in parentheses.
I guess I should use "author.name" if it's available, or parse "author" string to get that "clean" name (using simple regex to remove email and URL from it)

**Comment by szwacz** [comment]
I'm aware of that, but those specs are for npm and Firefox addons. Electron app is neather of them, so those restrictions don't apply, and we can do here pretty much whatever we want.
So personally I see no problem with having in that field only the name, without email. And by the way if someone wants to put his/her email in author field it won't break, just will look weird in windows manager.

**Comment by sviterok** [comment]
@szwacz Check this out. I just removed an email from the default "author" value in "package.json" and also added optional handling for scenario when developer has an object in that field (e.g. `{"name": "Mr Gumby", "email": "gumby@sillywalks.com", ...}`)

**Comment by szwacz** [comment]
Thanks! I've simplified your code and returned to `manifest.author` as-string-only use for two reasons:
1. This feature adds complexity for little gain. Also `author` field is also used in linux installer so implementing this feature over there adds even more complexity.
2. It wasn't documented (so like it never was there ;)

**Pull request merged**
