### PR TITLE
Fixes #37: Preload script must not be transpiled

### LINKED ISSUE #37: Transpiling not compatible with the preload option on BrowserWindow
The `preload` option is not working due to the build script:

````js
mainWindow = new BrowserWindow({
    // ... other options
    preload: path.join(__dirname, '/myPreloadedScript.js')
````

The built version (found under `/build` folder) is wrapped inside `define(['exports'], function (exports) {` leading to the following error:

````
ReferenceError: define is not defined
    at Object.<anonymous> (C:\electronApp\build\myPreloadedScript.js:1:63)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\electronApp\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\lib\init.js:94:7)
    at Object.<anonymous> (C:\electronApp\electronApp\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\lib\init.js:106:4)
    at Module._compile (module.js:430:26)(anonymous function) @ C:\electronApp\electronApp\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\lib\init.js:101
```` 

Preloaded js file should not be transpiled.
One PR will follow

### PR DESCRIPTION
**Pull request by antoinepairet**
See #37

### CODE REVIEW

**Comment by szwacz** [comment]
I'm very reluctant to add here code which will be useful only in small percentage of use cases.
What are practical implications of this preloaded script?

**Comment by antoinepairet** [comment]
@szwacz Thanks for your quick reply.
I am not sure what you mean with `practical implications`. But I will explain the use case more clearly. Imagine you already have a web application accessible from any browser. You want to extend this webapp into a desktop app. The extended version will be able to access the filesystem and communicate with devices connected to the desktop (USB, etc.).
In that use case, you want 2 things:

1. disable `node-integration` for the BrowserWindow and all scripts loaded by the webapp which is pure browser
2. `preload` a script with the desktop features. This script **needs**  `node-integration` 

(`web-preferences` from electron 0.32.2 API)
````js
mainWindow = new BrowserWindow({
    loadUrl: 'https://mySuperWebApp.com'
    'web-preferences': {
        'node-integration': false,
        preload: 'desktopAppExtension.js'
    }
})
````

The desktopAppExtenion will be loaded before any other script in the renderer process. You can define globals on the `window` object that will be used by the webapp.

I understand you want to keep things simple. If you prefer not to merge this PR, would you merge a documentation PR with the above comments?

kind regards

**Comment by szwacz** [comment]
I understand. This is very simple thing to configure in electron, so everyone can do it on their own :)
BUT your PR touched and attempts to fix this by editing the biggest pain of this project so far:
```js
var paths = {
    jsCodeToTranspile: [
        'app/**/*.js',
        '!app/main.js',
        '!app/spec.js',
        '!app/node_modules/**',
        '!app/vendor/**'
    ],
    copyFromAppDir: [
        './main.js',
        './spec.js',
        './node_modules/**',
        './vendor/**',
        './**/*.html'
    ],
}
```
And this piece of code is as I can see the biggest source of trouble right now. Everything has to be in one of those blocks, and has to be negated in the other. Without simplifying this thing we're going nowhere.

Best solution would be to use bundler with single file as a entry point (like browserify). Then code transpilation will be performed only on dependency tree which starts from e.g. app.js file.

Browserify is not an option because it will try to bundle native node modules as well, and we don't want that (snice we have node as first class citizen here).

I'm looking into https://github.com/rollup/rollup as we speak.

All ideas how to solve it are welcome!

**Comment by szwacz** [comment]
Problem has been solved by changing more fundamental design decisions.
Thanks for PR anyway :)

**Pull request closed without merging**
